### ISSUE TITLE
[Feature] Add support for introspection

### ISSUE THREAD

**Issue by alexstrat** [mesosphere/reactive-graphql#14]
Current implementation does not support [introspection](https://graphql.org/learn/introspection/).

Introspection is sometimes useful, especially because some graphql dev tools like [GraphiQL](https://github.com/graphql/graphiql) makes [use of it](https://github.com/graphql/graphiql/blob/7421b953b50fc58f54c213fa4634f499d51bd24e/src/utility/introspectionQueries.js#L13).

I don't think the implementation is that difficult as we can use `graphql-js` implementation almost directly.

**Comment by alexstrat** [comment]
A "reference introspection query" is [this one](https://github.com/graphql/graphql-js/blob/926e4d80c558b107c49e9403e943086fa9b043a8/src/utilities/introspectionQuery.js#L21).

**Comment by DanielMSchmidt** [comment]
Hey @alexstrat,

We have this feature on our internal roadmap, but it's currently far from top priority. As far as I understand this feature it has two use-cases:

1) Use `__typename` in a query

We might need to have this in the future for some switches, but it's currently not important for our use case

2) Introspection Queries by external tools

As far as I understood this these queries only get important for tooling which can not have access to the schema itself. For example, we use reactive-graphql in the browser and therefore have a schema at hand to directly provide it to GraphiQL.

That being said I will do my best to support you with this effort and review your PR 💪 Thanks for driving this so much 👍

**Comment by alexstrat** [comment]
I had no idea we could pass a schema directly to GraphiQL! Thanks! Actually, we are using GraphiQL inside Apollo Dev Tools (because we are using Apollo stack, as you have guessed), so we don't have this option, but good to know.

We'll see if it's a big deal for us to not have schema introspection, and I'll suggest a PR.

**Comment by alexstrat** [comment]
Closed via #28
