### ISSUE TITLE
Use 'getTypeMap' intead of '_typeMap'

### ISSUE THREAD

**Issue by IvanGoncharov** [mesosphere/reactive-graphql#7]
I was just looking through the source code and notice that you are using `_typeMap` you can use `getTypeMap` instead which is part of public API:
https://github.com/graphql/graphql-js/blob/5b17d41aa4c9095f21a256461cb4097829b3c9b5/src/type/schema.js#L200-L202

**Comment by nLight** [comment]
Hey Ivan! Thanks for the suggestion! We are open for patches if you would like to contribute :)
